name: Deploy

on: [workflow_dispatch]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.G_ACCESS_TOKEN }}
          workflow: deploy.yml
          branch: main
          repo: Shark-Company/sharkcompany-frontend
          name: production-files
          path: ./dist
          search_artifacts: true
          check_artifacts:  true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
