name: Deploy

on:
  workflow_dispatch:
    inputs:
      external_run_id:
        type: string
        description: Run id from build workflow

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Wait
        run: |
          echo "Wait"
          sleep 10s

      - name: Echo check external run id
        run: echo "run id - ${{ inputs.external_run_id }}"

      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.G_ACCESS_TOKEN }}
          run_id: ${{ inputs.external_run_id }}
          workflow: deploy.yml
          repo: Shark-Company/sharkcompany-frontend
          name: production-build
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
